name: in8_app
description: aplicativo será criado como teste de emprego

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  bloc_pattern: ^2.5.1
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  responsive_widgets: ^0.1.10
  html_color: ^1.0.1
  dio: ^3.0.9
  get: ^3.2.2
  flutter_spinkit: ^4.1.2
  sqflite: ^1.3.1+1
  path_provider: ^1.6.18

dev_dependencies:
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: 'assets/fonts/quicksand/Quicksand-Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/quicksand/Quicksand-Medium.ttf'
          weight: 500
        - asset: 'assets/fonts/quicksand/Quicksand-Regular.ttf'